#!/usr/bin/env python3
"""
Test script that makes a REAL call to Gemini LLM
This will actually use your API key and make a real request
"""

import os
import sys

# Add the parent directory to the path so we can import backend modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.models.core import UserRequest
from backend.agents.planner import PlannerAgent


def test_real_llm_call():
    """Test with a real LLM call (uses actual API key)"""
    
    print("=== REAL LLM Test ===\n")
    print("⚠️  This will make an actual API call to Google Gemini!")
    print("⚠️  This will use your API quota and may incur costs.\n")
    
    # Create a simple user request
    user_request = UserRequest(
        description="Build a simple todo app with add, delete, and mark complete features"
    )
    
    print(f"User Request: {user_request.description}")
    print(f"Session ID: {user_request.session_id}\n")
    
    try:
        # Create planner agent (this will use the real API key)
        print("Initializing Planner Agent with real Gemini API...")
        planner = PlannerAgent()
        print("✅ Planner Agent initialized successfully!\n")
        
        # Make the actual API call
        print("🚀 Making REAL API call to Gemini...")
        response = planner.analyze_request(user_request)
        
        if response.success:
            print("✅ REAL LLM call successful!")
            print(f"Execution time: {response.execution_time_ms}ms\n")
            
            plan = response.output['plan']
            
            print("📋 REAL Plan Generated by Gemini:")
            print(f"  • Pages: {len(plan['pages'])}")
            print(f"  • Components: {len(plan['components'])}")
            print(f"  • Complexity: {plan['estimated_complexity']}\n")
            
            print("📄 Pages from REAL LLM:")
            for page in plan['pages']:
                print(f"  • {page['name']} ({page['route']}) - {page['description']}")
            
            print("\n🧩 Components from REAL LLM:")
            for component in plan['components'][:3]:  # Show first 3 to keep output manageable
                print(f"  • {component['name']} ({component['type']}) - {component['description']}")
            
            if len(plan['components']) > 3:
                print(f"  ... and {len(plan['components']) - 3} more components")
            
            print(f"\n✅ This output came from REAL Gemini LLM, not hardcoded data!")
            
        else:
            print("❌ REAL LLM call failed!")
            for error in response.errors:
                print(f"  Error: {error}")
    
    except Exception as e:
        print(f"❌ Test failed: {str(e)}")
        if "API key" in str(e).lower():
            print("\n💡 This might be an API key issue. Check:")
            print("  1. Is GEMINI_API_KEY set in backend/.env?")
            print("  2. Is the API key valid and active?")
            print("  3. Is the Gemini API enabled in your Google Cloud project?")


if __name__ == "__main__":
    test_real_llm_call()