"""
Core Pydantic models for AMAR MVP
Contains UserRequest, Plan, and GeneratedProject models with validation
"""

from datetime import datetime
from typing import Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator, ConfigDict


class UserRequest(BaseModel):
    """
    Model for user input requests with validation
    Validates: Requirements 1.2
    """
    description: str
    session_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=datetime.now)

    @field_validator('description')
    @classmethod
    def validate_description(cls, v):
        """Validate that description is non-empty"""
        if not v or len(v.strip()) == 0:
            raise ValueError('Description cannot be empty')
        return v.strip()


class PageSpec(BaseModel):
    """Specification for a single page in the application"""
    name: str
    route: str
    components: List[str]
    description: str


class ComponentSpec(BaseModel):
    """Specification for a React component"""
    name: str
    type: str  # 'functional' | 'class' | 'hook'
    props: Dict[str, str] = Field(default_factory=dict)
    description: str


class RoutingConfig(BaseModel):
    """Configuration for React Router setup"""
    base_path: str = "/"
    routes: List[Dict[str, str]]  # [{"path": "/about", "component": "About"}]
    navigation_links: List[Dict[str, str]] = Field(default_factory=list)


class BackendSpec(BaseModel):
    """Specification for backend API endpoints"""
    endpoints: List[Dict[str, str]]  # [{"method": "POST", "path": "/api/contact", "handler": "handleContact"}]
    middleware: List[str] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list)


class Plan(BaseModel):
    """
    Structured plan generated by Planner Agent
    Validates: Requirements 2.2
    """
    pages: List[PageSpec]
    components: List[ComponentSpec]
    routing: RoutingConfig
    backend_logic: Optional[BackendSpec] = None
    estimated_complexity: str = "simple"  # simple | medium | complex
    
    @field_validator('pages')
    @classmethod
    def validate_page_count(cls, v):
        """Validate that page count doesn't exceed 5"""
        if len(v) > 5:
            raise ValueError(f'Page count ({len(v)}) exceeds maximum of 5 pages')
        return v

    @field_validator('pages')
    @classmethod
    def validate_pages_not_empty(cls, v):
        """Validate that at least one page is specified"""
        if len(v) == 0:
            raise ValueError('At least one page must be specified')
        return v


class TestResults(BaseModel):
    """Results from pytest execution"""
    passed: int = 0
    failed: int = 0
    errors: List[str] = Field(default_factory=list)
    execution_time_ms: int = 0
    coverage_percent: Optional[float] = None


class AuditLogEntry(BaseModel):
    """Single entry in the audit log"""
    timestamp: str
    session_id: str
    agent: str
    action: str
    details: Dict
    duration_ms: Optional[int] = None


class FileLineage(BaseModel):
    """Lineage tracking for generated files"""
    file_path: str
    created_by: str
    created_at: str
    modified_by: List[str] = Field(default_factory=list)
    reason: str


class GeneratedProject(BaseModel):
    """
    Complete generated project with all metadata
    Validates: Requirements 3.2
    """
    session_id: str
    files: Dict[str, str]  # filepath -> content
    plan: Plan
    test_results: TestResults
    deployment_url: Optional[str] = None
    audit_log: List[AuditLogEntry] = Field(default_factory=list)
    lineage: List[FileLineage] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.now)
    
    @field_validator('files')
    @classmethod
    def validate_files_not_empty(cls, v):
        """Validate that at least some files are generated"""
        if len(v) == 0:
            raise ValueError('Generated project must contain at least one file')
        return v


class AgentResponse(BaseModel):
    """Standard response format for all agents"""
    agent_name: str
    success: bool
    output: Dict
    errors: List[str] = Field(default_factory=list)
    execution_time_ms: int